Update (#1)
* Refactor event propagation in CanvasView

* Update SVG dimension icon styles

* Add `appendTo` option to TraitManager

* Update traits styles

* Refactor font size styles

* Update styles for selectors

* Add `silentFrames` option in Resizer

* Add `avoidContainerUpdate` option in Resizer

* Update panel style

* Append the modal inside the container and not the editor element

* Update canvas offset on resize of panels

* Add new 'freezed-selected' status for a component

* Remove some legacy code from Assets

* Update font style

* Test build

* Update npm dependencies

* Fix undo manager when moving components

* Bump v0.14.5

*  * Added css to hide very large labels.
 * Added title to label class, thus it shows the text on a tooltip.

* Don't trigger `component:add` when components are just moved. Fixes #868

* Pass response to 'editor.store(clb)' callback. Closes #876

* Escape title inside blocks

* Init correctly components with javascript. Fixes #873

* Fixed TypeError when canvas has been removed.

* prevent grapes.js from being injected twice during development

* show message in trait manager panel when there is no comp selected

* add failing unit test

* modify Component.toHTML to property encode attribute values

* Refactor few methods in Canvas

* Refactor OpenTraitManager

* escpae quotes in Component.toHTML

* use config.baseCss in canvasView if set in config

* add baseCss overwrite documentation

* wip test case

* revert previous test change

* Check if the attribute is a string before replacing

* Manage correctly boolean attributes in HTML output. Fixes #943

* Once the id rule is created in Component, clean its internal style

* enabled iframes in jsdoc and added positive and negative tests for baseCss overwriting feature

* removed redudandant options and global

* Fix block text overflow. Closes #946

* Fix the import of components and styles with the same ids. Fixes #932

* Bump v0.14.6

* Updated block_manager config.js

removed duplicated property

* Fix some issues in IE11 #768

* Check if the event exists in move command. Fixes #710

* keep readme clean

* Fix youtube loop parameter in Video Component. Fixes #969

* Remove controls option for Vimeo videos as it's only for PRO users. Closes #977

* Add new Command lifecycle events

* Add `core:component-delete` command

* Make font size variables overridable

* Update storage:load event

* Added style containers to fix styles/media-query order

* Avoid adding CssRules with empty style object

* Check if loaded CSS is actually empty

* Don't stringify `script`s function in toJSON method. Fixes #980

* Fixed tests

* Removed unused require

* Fix loading with autoload but without the storage

* Fix `append` method in JsContainer

* Add a monkey patch for the cash's `removeClass` to make it work with IE #768

* Cache the return of `getClearEl`. Fixes #768

* Listen traits change on components

* implemented removeEmptyTextNodes boolean (defaults to true to prevent breaking changes); fixes #989

* negative strict equality check because config is not always available in test suite

* Applied fixes and improvements based on PR comments

* Fixed tests - replaced getElementById with querySelector to avoid "getElementById is not a function" error

* Add `storage:store:before` event

* Add `avoidDefaults` option

* Revert "implemented removeEmptyTextNodes boolean, fixes #989"

* Get mediaCondition from Editor model config. Fixed tests - add storable to Editor model, proper CssComposer init

* Refactor ‘open-assets’ editor command to permit arbitrary file types

The file types can be passed as a config option for an asset type in which case the types will be used to limit the accepted file type when uploading new files in the asset manager.

* added test cases for multiple font faces

* Ignore yarn files so contributors can use it

* Support percentage based media-widths

* allow for multiple at-rules

* Add more storage events
`storage:start:store`, `storage:start:load`, `storage:end:store`, `storage:end:load`

* Less strict on boolean types

* Rename option `removeEmptyTextNodes` -> `keepEmptyTextNodes`

* Support no-name traits

* Fix CSS rule rendering with custom media rules

* Clean ButtonView form useless code

* Add `label` property to buttons. Closes #1031

* Prevent `null` contRules in CssRulesView

* Bump v0.14.9

* Add no-response bot

* Clean ws

* Returning result from CommandAbstract's callRun and callStop functions. Fixes https://github.com/artf/grapesjs/issues/1051

* Update store after changes to css

* first commit

* Make the UndoManager listen for rules changes

* Refactor handleChange

* Add BrowserStack badge

* added unit testing to dump unused css selectors

* rename variable

* addded new config option dumpUnusedStyles as false by default

* unit tests

* added styleable events such that styling can be overwritten

* Clean ExportTemplate command

* Fix resizer selection on blur

* Update the selected event in SelectComponent

* Ensure the resizer focus on selected component

* refactor - rename variable

* added keepUnusedStyles functionality for media rules

* ‘open-assets’ - Simplify by adding an ‘accept’ option

* Refactor `OpenAssets` command

* Update README

* Bump v0.14.10

* Update README.md

* Add get `getDirtyCount` method

* Improve `storage:error` event and add 2 other events
Other events are `storage:error:load` and `storage:error:store`

* Pass error callback to remote storage

* Add `replaceWith` method to Component

* Bind handleAdd to AssetsView

* Bump v0.14.15

* Update README

* Trigger change for empty value in traits. Fixes #270

* Add ComponentLabel and avoid its bounds via for. Closes #316

* Make the component hoverable through the state

* Highlight components in canvas on hover in Layers. Closes #423

* Move the undo manager stop in getModelToStyle

* Fix issues with color traits. Fixes #1104

* Improve toJSON of CSSRule

* Add `scrollTo` method to the Canvas module

* Add `scrollCanvas` option in Layers

* Fix layers opening

* Scroll to the selected layer when a component is selected

* Clean mixins

* Update hovered state in layers

* Add `highlightHover` option in Layers

* Add `remove` listener on panel items. Fixes #1081

* Add condition to check if the edit image button already exists

* Fixes

* Add component's type to its view via `data-type` attribute

* 'data-type' -> 'data-gjs-type'

* Refactor components

* Update toolbars position when text components are updated. Closes #1136

* Fix regressions

* Soft deps update

* Update more deps

* Prepare jest

* Adjust imports

* use jest-codemods

* Update tests for jest

* Clean deps

* Update deps

* Update gitignore

* Update the class parser in HTML

* Fix regressions

* Try to find a closest model when an element, without it, is selected

* Bump v0.14.17

* Add selected collection in editor and move component remove logic

* Add getModel to mixins

* Refactor DomComponents selection methods

* Move selectedComponent events to DomComponents

* Use `component:selected` in OpenStyleManager

* Remove 'change:selectedComponent' from SectorsView

* Add `component:toggled` event and update OpenTraitManager

* Remove selectedComponent reference in SelectComponent

* Remove selectedComponent reference in ClassTagsView

* Remove `change:selectedComponent` from other modules

* Remove selectedComponent references

* Add removeChildren to ItemsView in Layers

* Support multiple removing

* Support multiple cloning

* Refactor copy and paste commands

* Refactor `clear` method in DomComponents

* Support multiple moving

* Refactor the Sorter

* Add `multipleSelection` option

* Manage multiple selection with StyleManager and TraitManager

* Refactor selection and avoid useless removes

* Update getElement

* Add new commands and they relative keymaps for easy navigate through the structure:
* `core:component-prev` (w)
* `core:component-next` (s)
* `core:component-enter` (d)
* `core:component-exit` (a)

* Fix regressions

* Add component selection tests

* Parse important declarations in style properties. Fixes #1179

* Add tests for important in style properties

* Add selection via shift key

* Navigate components only if the canvas is focused

* Add deprecated events warning

* Add destroy method

* Render Layers always via Model

* Add `setRoot` to Layers

* Add `getRoot` method

* Add the possibility to init the LayerManager with a different root

* Fix tests

* Update remove on component collections

* Update structure navigation commands

* Update Style Manager listener

* Avoid content to be deleted from defaults in toJSON
This prevents issues with UndoManager

* Bump v0.14.20

* Updated keymaster dependency version.